-- USUARIO
CREATE TABLE USUARIO (
	IDUSUARIO 		BIGINT 			PRIMARY KEY,
	NOME 			VARCHAR(255) 	NOT NULL,
	ADMINISTRADOR	BOOLEAN			DEFAULT FALSE,
	LOGIN 			VARCHAR(255) 	NOT NULL,
	SENHA 			VARCHAR(255) 	NOT NULL

);

CREATE SEQUENCE IDUSUARIO;

---------------------------------------------

-- TIPOPESSOA

CREATE TABLE TIPOPESSOA (
	IDTIPOPESSOA 	BIGINT 			PRIMARY KEY,
	CODIGO 			BIGINT 			NOT NULL,
	DESCRICAO 		VARCHAR(255) 	NOT NULL
);

---------------------------------------------

-- TIPOVEICULO

CREATE TABLE TIPOVEICULO (
	IDTIPOVEICULO 	BIGINT 			PRIMARY KEY,
	CODIGO 			BIGINT 			NOT NULL,
	DESCRICAO 		VARCHAR(255) 	NOT NULL
);

---------------------------------------------

-- PESSOA

CREATE TABLE PESSOA (
	IDPESSOA 		BIGINT 			PRIMARY KEY,
	IDTIPOPESSOA 	BIGINT 			NOT NULL,
	CPFCNPJ 		VARCHAR(14) 	NOT NULL,
	NOME			VARCHAR(255)	NOT NULL,
	EMAIL 			VARCHAR(255) 	NOT NULL,
	TELEFONE 		VARCHAR(400)	NOT NULL,
	CONSTRAINT FKPESSOATIPOPESSOA FOREIGN KEY (IDTIPOPESSOA) REFERENCES TIPOPESSOA(IDTIPOPESSOA),
	CONSTRAINT UNIQUECPFCNPJPESSOA UNIQUE(CPFCNPJ)
);

CREATE SEQUENCE IDPESSOA;

---------------------------------------------

-- VEICULO

CREATE TABLE VEICULO (
	IDVEICULO 		BIGINT 			PRIMARY KEY,
	IDTIPOVEICULO 	BIGINT 			NOT NULL,
	PLACA 			VARCHAR(7) 		NOT NULL,
	MODELO 			VARCHAR(255) 	NOT NULL,
	MARCA 			VARCHAR(255) 	NOT NULL,
	ANO 			BIGINT 			NOT NULL,
	CONSTRAINT FKVEICULOTIPOVEICULO FOREIGN KEY (IDTIPOVEICULO) REFERENCES TIPOVEICULO(IDTIPOVEICULO),
	CONSTRAINT UNIQUEPLACAVEICULO UNIQUE(PLACA)
);

CREATE SEQUENCE IDVEICULO;

---------------------------------------------

-- PESSOAVEICULO

CREATE TABLE PESSOAVEICULO (
	IDPESSOAVEICULO BIGINT 			PRIMARY KEY,
	IDPESSOA 		BIGINT 			NOT NULL,
	IDVEICULO 		BIGINT 			NOT NULL,
	CONSTRAINT FKPESSOAVEICULOPESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA),
	CONSTRAINT FKPESSOAVEICULOVEICULO FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);

CREATE SEQUENCE IDPESSOAVEICULO;

---------------------------------------------

-- VEICULOIDENTIFICACAO 

CREATE TABLE VEICULOIDENTIFICACAO (
	IDVEICULOIDENTIFICACAO 	BIGINT 			PRIMARY KEY,
	IDVEICULO 				BIGINT 			NOT NULL,
	UUID 					VARCHAR(512) 	NOT NULL,
	CONSTRAINT VEICULOIDENTIFICACAOVEICULO FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);

CREATE SEQUENCE IDVEICULOIDENTIFICACAO;

---------------------------------------------

-- LEITOR

CREATE TABLE LEITOR (
	IDLEITOR 				BIGINT 			PRIMARY KEY,
	ENDERECO 				VARCHAR(15)		NOT NULL,
	DESCRICAO 				VARCHAR(255) 	NOT NULL
);

CREATE SEQUENCE IDLEITOR;







